name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Clean Deploy Directory
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@10.25.84.2 "rm -rf /var/www/destxpert.travel/*"

      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/id_rsa -r dist/ root@10.25.84.2:/var/www/destxpert.travel/
