name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Install SSTP VPN Client
        run: |
          sudo apt-get update
          sudo apt-get install -y sstp-client ppp iproute2 net-tools

      - name: Connect to VPN
        run: |
          sudo sstpc --log-stderr --cert-warn --user "${{ secrets.VPN_USER }}" --password "${{ secrets.VPN_PASSWORD }}" \
          gate.destxpert.travel:442 usepeerdns require-mschap-v2 refuse-eap noauth &

      - name: Wait for VPN
        run: sleep 10 # даем время для установки VPN

      - name: Debug VPN Connection
        run: |
          echo "Checking VPN connection..."
          ip route
          ifconfig
          ps aux | grep sstpc || echo "VPN process not running"

      - name: Add VPN Route
        run: |
          echo "Adding VPN route..."
          sudo ip route add 10.25.84.0/24 dev ppp0 || echo "Failed to add VPN route"

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH Key
        run: |
          echo "Checking SSH Key..."
          ls -la ~/.ssh/
          cat ~/.ssh/id_rsa || echo "SSH Key not found or empty."

      - name: Test VPN Connection
        run: |
          echo "Pinging the server through VPN..."
          ping -c 4 10.25.84.2 || echo "Ping failed. Check VPN connection or server availability."

      - name: Check SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@10.25.84.2 "echo 'SSH connection successful'" || echo "SSH connection failed."

      - name: Clean Deploy Directory
        run: |
          echo "Cleaning up remote directory..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@10.25.84.2 "rm -rf /var/www/destxpert.travel/*" || echo "Failed to clean deploy directory."

      - name: Deploy to Server
        run: |
          echo "Deploying dist/ to server..."
          scp -i ~/.ssh/id_rsa -r dist/* root@10.25.84.2:/var/www/destxpert.travel/ || echo "SCP failed. Check the logs above."
